project: 
  type: website
  output-dir: docs

execute:
  freeze: auto
  
website:
  page-navigation: true  
  title: "NOAA Fisheries GitHub Clinic"
  favicon: "images/favicon-16x16.png"
  site-url: https://nmfs-opensci.github.io/GitHub-Clinic
  repo-url: https://github.com/nmfs-opensci/GitHub-Clinic
  repo-actions: [edit, issue, source]
  
  page-footer: <img src="https://github.com/nmfs-opensci/assets/blob/main/logo/nmfs-opensci-logo2.png?raw=true" alt="NMFS Open Science logo" style="width:150px"><br />NMFS Open Science (2023)

  navbar:
    background: primary
    search: true
    right: 
      - icon: server
        href: https://nmfs-openscapes.2i2c.cloud/
        text: "JupyterHub"
      - icon: wechat
        href: https://chat.google.com/room/AAAAJ6cl1_4?cls=7
        text: "Discussions"
      - icon: github
        href: https://github.com/nmfs-opensci/GitHub-Clinic
        text: "repo"
      - icon: globe
        href: https://github.com/nmfs-opensci
        text: "GH org"
  sidebar:
    logo: https://github.com/nmfs-opensci/assets/blob/main/logo/nmfs-opensci-logo2.png?raw=true
    pinned: true
    align: center
    
    style: "docked"
    collapse-level: 1
    toc-expand: false
    contents:
      - section: "Welcome"
        href: index.qmd
        contents:
          - team.md
          - schedule.md
          - section: Set-up - Coming soon!
#            - text: Git-JupyterLab
#              href: content/02-git-jupyter.md
#            - text: Git-RStudio
#              href: content/02-git-rstudio.md
          - coc.md
      - section: "Resources - Coming Soon!"
      - section: "Tutorials - Coming soon!"
      - text: <img width=100px>
      - text: <img width=100px>
      - text: <img src="/images/noaa_emblem_logo-2022.png" width=100px>
        href: https://fisheries.noaa.gov
format:
  html:
    theme:
      light: cosmo
      dark: [cosmo, theme-dark.scss]
    code-background: true
    code-copy: true
    css: styles.css
    toc: true
    toc-depth: 2
    include-before-body: translate.html

#filters:
#  - include-files.lua
#  - quarto
